## Data cleaning and preparation

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('data/raw/Netflix.csv')

In [7]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [8]:
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,25-Sep-21,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,24-Sep-21,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,24-Sep-21,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,24-Sep-21,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,24-Sep-21,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
195,s196,Movie,EMI: Liya Hai To Chukana Padega,Saurabh Kabra,"Sanjay Dutt, Arjun Rampal, Malaika Arora, Aash...",India,27-Aug-21,2008,TV-14,128 min,"Comedies, Dramas, International Movies",A bank hires an enigmatic and unorthodox debt ...
196,s197,Movie,He's All That,Mark Waters,"Addison Rae, Tanner Buchanan, Rachael Leigh Co...",NaN,27-Aug-21,2021,TV-14,92 min,"Comedies, Romantic Movies",An influencer specializing in makeovers bets s...
197,s198,TV Show,I Heart Arlo,NaN,"Michael J. Woodard, Mary Lambert, Jonathan Van...",NaN,27-Aug-21,2021,TV-Y7,1 Season,"Kids' TV, TV Comedies",It's a whole new world for Arlo and his one-of...
198,s199,TV Show,King of Boys: The Return of the King,Kemi Adetiba,"Sola Sobowale, Toni Tones, Richard Mofe-Damijo...",Nigeria,27-Aug-21,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas",Alhaja Eniola Salami starts anew and sets her ...
199,s200,Movie,Koi Aap Sa,Partho Mitra,"Aftab Shivdasani, Natassha, Dipannita Sharma, ...",India,27-Aug-21,2006,TV-14,135 min,"Comedies, Dramas, International Movies",Star athlete Rohan has his eye on a beautiful ...

In [7]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [8]:
critical_columns = ['show_id', 'title', 'type', 'release_year', 'duration']
df = df.dropna(subset=critical_columns)

In [9]:
critical_columns = ['show_id', 'title', 'type', 'release_year', 'duration']
df = df.dropna(subset=critical_columns)
# Выбираем только строковые (object) колонки
string_columns = df.select_dtypes(include=['object']).columns

# Применяем strip() и lower() ко всем строкам в этих колонках
df[string_columns] = df[string_columns].apply(lambda x: x.str.strip().str.lower())
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,movie,dick johnson is dead,kirsten johnson,NaN,united states,25-sep-21,2020,pg-13,90 min,documentaries,"as her father nears the end of his life, filmm..."
1,s2,tv show,blood & water,NaN,"ama qamata, khosi ngema, gail mabalane, thaban...",south africa,24-sep-21,2021,tv-ma,2 seasons,"international tv shows, tv dramas, tv mysteries","after crossing paths at a party, a cape town t..."
2,s3,tv show,ganglands,julien leclercq,"sami bouajila, tracy gotoas, samuel jouy, nabi...",NaN,24-sep-21,2021,tv-ma,1 season,"crime tv shows, international tv shows, tv act...",to protect his family from a powerful drug lor...
3,s4,tv show,jailbirds new orleans,NaN,NaN,NaN,24-sep-21,2021,tv-ma,1 season,"docuseries, reality tv","feuds, flirtations and toilet talk go down amo..."
4,s5,tv show,kota factory,NaN,"mayur more, jitendra kumar, ranjan raj, alam k...",india,24-sep-21,2021,tv-ma,2 seasons,"international tv shows, romantic tv shows, tv ...",in a city of coaching centers known to train i...
...,...,...,...,...,...,...,...,...,...,...,...,...
195,s196,movie,emi: liya hai to chukana padega,saurabh kabra,"sanjay dutt, arjun rampal, malaika arora, aash...",india,27-aug-21,2008,tv-14,128 min,"comedies, dramas, international movies",a bank hires an enigmatic and unorthodox debt ...
196,s197,movie,he's all that,mark waters,"addison rae, tanner buchanan, rachael leigh co...",NaN,27-aug-21,2021,tv-14,92 min,"comedies, romantic movies",an influencer specializing in makeovers bets s...
197,s198,tv show,i heart arlo,NaN,"michael j. woodard, mary lambert, jonathan van...",NaN,27-aug-21,2021,tv-y7,1 season,"kids' tv, tv comedies",it's a whole new world for arlo and his one-of...
198,s199,tv show,king of boys: the return of the king,kemi adetiba,"sola sobowale, toni tones, richard mofe-damijo...",nigeria,27-aug-21,2021,tv-ma,1 season,"crime tv shows, international tv shows, tv dramas",alhaja eniola salami starts anew and sets her ...
199,s200,movie,koi aap sa,partho mitra,"aftab shivdasani, natassha, dipannita sharma, ...",india,27-aug-21,2006,tv-14,135 min,"comedies, dramas, international movies",star athlete rohan has his eye on a beautiful ...

In [10]:
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')

C:\Users\user\AppData\Local\Temp\ipykernel_21348\2314529673.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')

In [11]:
df['month_added'] = df['date_added'].dt.month
df['country'] = df['country'].fillna('Unknown')
df['director'] = df['director'].fillna('Unknown')
df['cast'] = df['cast'].fillna('Unknown')
df['listed_in'] = df['listed_in'].fillna('Unknown')
df['duration'] = df['duration'].fillna('Unknown')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       200 non-null    object
 1   type          200 non-null    object
 2   title         200 non-null    object
 3   director      200 non-null    object
 4   cast          200 non-null    object
 5   country       200 non-null    object
 6   date_added    200 non-null    datetime64[ns]
 7   release_year  200 non-null    int64
 8   rating        200 non-null    object
 9   duration      200 non-null    object
 10  listed_in     200 non-null    object
 11  description   200 non-null    object
 12  month_added   200 non-null    int32
dtypes: datetime64[ns](1), int32(1), int64(1), object(10)
memory usage: 19.7+ KB

In [50]:
#Приведем типы данных в порядок
string_cols = ['show_id', 'title', 'director', 'cast', 'country', 'duration', 'listed_in', 'description']

df[string_cols] = df[string_cols].astype('string')

In [51]:
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,month_added
0,s1,movie,dick johnson is dead,kirsten johnson,Unknown,united states,2021-09-25,2020,pg-13,90 min,documentaries,"as her father nears the end of his life, filmm...",9
1,s2,tv show,blood & water,Unknown,"ama qamata, khosi ngema, gail mabalane, thaban...",south africa,2021-09-24,2021,tv-ma,2 seasons,"international tv shows, tv dramas, tv mysteries","after crossing paths at a party, a cape town t...",9
2,s3,tv show,ganglands,julien leclercq,"sami bouajila, tracy gotoas, samuel jouy, nabi...",Unknown,2021-09-24,2021,tv-ma,1 season,"crime tv shows, international tv shows, tv act...",to protect his family from a powerful drug lor...,9
3,s4,tv show,jailbirds new orleans,Unknown,Unknown,Unknown,2021-09-24,2021,tv-ma,1 season,"docuseries, reality tv","feuds, flirtations and toilet talk go down amo...",9
4,s5,tv show,kota factory,Unknown,"mayur more, jitendra kumar, ranjan raj, alam k...",india,2021-09-24,2021,tv-ma,2 seasons,"international tv shows, romantic tv shows, tv ...",in a city of coaching centers known to train i...,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,s196,movie,emi: liya hai to chukana padega,saurabh kabra,"sanjay dutt, arjun rampal, malaika arora, aash...",india,2021-08-27,2008,tv-14,128 min,"comedies, dramas, international movies",a bank hires an enigmatic and unorthodox debt ...,8
196,s197,movie,he's all that,mark waters,"addison rae, tanner buchanan, rachael leigh co...",Unknown,2021-08-27,2021,tv-14,92 min,"comedies, romantic movies",an influencer specializing in makeovers bets s...,8
197,s198,tv show,i heart arlo,Unknown,"michael j. woodard, mary lambert, jonathan van...",Unknown,2021-08-27,2021,tv-y7,1 season,"kids' tv, tv comedies",it's a whole new world for arlo and his one-of...,8
198,s199,tv show,king of boys: the return of the king,kemi adetiba,"sola sobowale, toni tones, richard mofe-damijo...",nigeria,2021-08-27,2021,tv-ma,1 season,"crime tv shows, international tv shows, tv dramas",alhaja eniola salami starts anew and sets her ...,8
199,s200,movie,koi aap sa,partho mitra,"aftab shivdasani, natassha, dipannita sharma, ...",india,2021-08-27,2006,tv-14,135 min,"comedies, dramas, international movies",star athlete rohan has his eye on a beautiful ...,8

In [52]:
title_df = df[['show_id', 'title', 'type', 'cast', 'release_year', 'rating', 'duration', 'description']]

title_df['duration'] = title_df['duration'].str.extract('(\d+)').astype(int)

title_df

C:\Users\user\AppData\Local\Temp\ipykernel_23560\2018299408.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  title_df['duration'] = title_df['duration'].str.extract('(\d+)').astype(int)

,show_id,title,type,cast,release_year,rating,duration,description
0,s1,dick johnson is dead,movie,Unknown,2020,pg-13,90,"as her father nears the end of his life, filmm..."
1,s2,blood & water,tv show,"ama qamata, khosi ngema, gail mabalane, thaban...",2021,tv-ma,2,"after crossing paths at a party, a cape town t..."
2,s3,ganglands,tv show,"sami bouajila, tracy gotoas, samuel jouy, nabi...",2021,tv-ma,1,to protect his family from a powerful drug lor...
3,s4,jailbirds new orleans,tv show,Unknown,2021,tv-ma,1,"feuds, flirtations and toilet talk go down amo..."
4,s5,kota factory,tv show,"mayur more, jitendra kumar, ranjan raj, alam k...",2021,tv-ma,2,in a city of coaching centers known to train i...
...,...,...,...,...,...,...,...,...
195,s196,emi: liya hai to chukana padega,movie,"sanjay dutt, arjun rampal, malaika arora, aash...",2008,tv-14,128,a bank hires an enigmatic and unorthodox debt ...
196,s197,he's all that,movie,"addison rae, tanner buchanan, rachael leigh co...",2021,tv-14,92,an influencer specializing in makeovers bets s...
197,s198,i heart arlo,tv show,"michael j. woodard, mary lambert, jonathan van...",2021,tv-y7,1,it's a whole new world for arlo and his one-of...
198,s199,king of boys: the return of the king,tv show,"sola sobowale, toni tones, richard mofe-damijo...",2021,tv-ma,1,alhaja eniola salami starts anew and sets her ...
199,s200,koi aap sa,movie,"aftab shivdasani, natassha, dipannita sharma, ...",2006,tv-14,135,star athlete rohan has his eye on a beautiful ...

In [55]:
directors_df = df[df['director'] != 'Unknown'][['director']].copy()

directors_df['director'] = directors_df['director'].astype('string')

df['director'] = df['director'].str.split(', ')

df = df.explode('director')

directors_df = directors_df.drop_duplicates()  # Удаление повторяющихся строк

directors_df = directors_df.reset_index(drop=True)

directors_df

            director
0    kirsten johnson
1    julien leclercq
2      mike flanagan
3      robert cullen
4     josé luis ucha
..               ...
135  taylor sheridan
136     sachin yardi
137    saurabh kabra
138      mark waters
139     partho mitra

[140 rows x 1 columns]

In [56]:
directors_df['director_id'] = [f'r{i+1}' for i in range(len(directors_df))]

directors_df['director_id'] = directors_df['director_id'].astype('string')

directors_df

            director director_id
0    kirsten johnson          r1
1    julien leclercq          r2
2      mike flanagan          r3
3      robert cullen          r4
4     josé luis ucha          r5
..               ...         ...
135  taylor sheridan        r136
136     sachin yardi        r137
137    saurabh kabra        r138
138      mark waters        r139
139     partho mitra        r140

[140 rows x 2 columns]

In [68]:
directors_df.to_csv('directors.csv', index=False)

In [63]:
df1 = pd.read_csv('data/raw/Netflix.csv')

df1 = df1[['show_id', 'title', 'director', 'country', 'listed_in']]

df1['director'] = df1['director'].str.split(', ')

df1 = df1.explode('director')

df1['country'] = df1['country'].str.split(', ')

df1 = df1.explode('country')

df1['listed_in'] = df1['listed_in'].str.split(', ')

df1 = df1.explode('listed_in')


df1

,show_id,title,director,country,listed_in
0,s1,Dick Johnson Is Dead,Kirsten Johnson,United States,Documentaries
1,s2,Blood & Water,NaN,South Africa,International TV Shows
1,s2,Blood & Water,NaN,South Africa,TV Dramas
1,s2,Blood & Water,NaN,South Africa,TV Mysteries
2,s3,Ganglands,Julien Leclercq,NaN,Crime TV Shows
...,...,...,...,...,...
198,s199,King of Boys: The Return of the King,Kemi Adetiba,Nigeria,International TV Shows
198,s199,King of Boys: The Return of the King,Kemi Adetiba,Nigeria,TV Dramas
199,s200,Koi Aap Sa,Partho Mitra,India,Comedies
199,s200,Koi Aap Sa,Partho Mitra,India,Dramas
199,s200,Koi Aap Sa,Partho Mitra,India,International Movies

In [69]:
df1.to_csv('df1.csv', index=False)

In [75]:
countries_df = df[df['country'] != 'Unknown'][['country']].copy()

countries_df['country'] = countries_df['country'].astype('string')

df['country'] = df['country'].str.split(', ')

df = df.explode('country')

countries_df = countries_df.drop_duplicates()  # Удаление повторяющихся строк

countries_df = countries_df.reset_index(drop=True)

countries_df

           country
0    united states
1     south africa
2            india
3            ghana
4     burkina faso
5   united kingdom
6          germany
7         ethiopia
8   czech republic
9           mexico
10          turkey
11       australia
12          france
13         finland
14           china
15          canada
16           japan
17         nigeria
18           spain
19         belgium
20     south korea
21       singapore
22           italy
23         romania
24       argentina
25       venezuela
26       hong kong
27          russia
28

In [78]:
countries_df = countries_df[countries_df['country'] != '']
countries_df

           country
0    united states
1     south africa
2            india
3            ghana
4     burkina faso
5   united kingdom
6          germany
7         ethiopia
8   czech republic
9           mexico
10          turkey
11       australia
12          france
13         finland
14           china
15          canada
16           japan
17         nigeria
18           spain
19         belgium
20     south korea
21       singapore
22           italy
23         romania
24       argentina
25       venezuela
26       hong kong
27          russia

In [81]:
countries_df['country_id'] = [f'с{i+1}' for i in range(len(countries_df))]

countries_df['country_id'] = countries_df['country_id'].astype('string')

countries_df

C:\Users\user\AppData\Local\Temp\ipykernel_23560\2999011485.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  countries_df['country_id'] = [f'с{i+1}' for i in range(len(countries_df))]
C:\Users\user\AppData\Local\Temp\ipykernel_23560\2999011485.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  countries_df['country_id'] = countries_df['country_id'].astype('string')

           country country_id
0    united states         с1
1     south africa         с2
2            india         с3
3            ghana         с4
4     burkina faso         с5
5   united kingdom         с6
6          germany         с7
7         ethiopia         с8
8   czech republic         с9
9           mexico        с10
10          turkey        с11
11       australia        с12
12          france        с13
13         finland        с14
14           china        с15
15          canada        с16
16           japan        с17
17         nigeria        с18
18           spain        с19
19         belgium        с20
20     south korea        с21
21       singapore        с22
22           italy        с23
23         romania        с24
24       argentina        с25
25       venezuela        с26
26       hong kong        с27
27          russia        с28

In [83]:
countries_df.to_csv('countries.csv', index=True)

In [87]:
genres_df = df[df['listed_in'] != 'Unknown'][['listed_in']].copy()

genres_df = genres_df.rename(columns={'listed_in': 'genre'})

genres_df['genre'] = genres_df['genre'].astype('string')

genres_df['genre'] = genres_df['genre'].str.split(', ')

genres_df = genres_df.explode('genre')

genres_df = genres_df.drop_duplicates()  # Удаление повторяющихся строк

genres_df = genres_df.reset_index(drop=True)

genres_df = genres_df[genres_df['genre'] != '']

genres_df['genre_id'] = [f'g{i+1}' for i in range(len(genres_df))]

genres_df['genre_id'] = genres_df['genre_id'].astype('string')

genres_df

                        genre genre_id
0               documentaries       g1
1      international tv shows       g2
2                   tv dramas       g3
3                tv mysteries       g4
4              crime tv shows       g5
5       tv action & adventure       g6
6                  docuseries       g7
7                  reality tv       g8
8           romantic tv shows       g9
9                 tv comedies      g10
10                  tv horror      g11
11   children & family movies      g12
12                     dramas      g13
13         independent movies      g14
14       international movies      g15
15           british tv shows      g16
16                   comedies      g17
17  spanish-language tv shows      g18
18                  thrillers      g19
19            romantic movies      g20
20           music & musicals      g21
21              horror movies      g22
22           sci-fi & fantasy      g23
23               tv thrillers      g24
24                   kids' tv      g25
25         action & adventure      g26
26        tv sci-fi & fantasy      g27
27             classic movies      g28
28             anime features      g29
29              sports movies      g30
30               anime series      g31
31            korean tv shows      g32
32        science & nature tv      g33
33              teen tv shows      g34
34                cult movies      g35
35                   tv shows      g36
36       faith & spirituality      g37
37               lgbtq movies      g38

In [88]:
genres_df.to_csv('genres.csv', index=True)

In [91]:
added_info_df = df[['show_id', 'date_added', 'month_added']]
added_info_df

    show_id date_added  month_added
0        s1 2021-09-25            9
1        s2 2021-09-24            9
2        s3 2021-09-24            9
3        s4 2021-09-24            9
4        s5 2021-09-24            9
..      ...        ...          ...
195    s196 2021-08-27            8
196    s197 2021-08-27            8
197    s198 2021-08-27            8
198    s199 2021-08-27            8
199    s200 2021-08-27            8

[268 rows x 3 columns]

In [95]:
added_info_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 268 entries, 0 to 199
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   show_id      268 non-null    string
 1   date_added   268 non-null    datetime64[ns]
 2   month_added  268 non-null    int32
dtypes: datetime64[ns](1), int32(1), string(1)
memory usage: 15.4 KB

In [98]:
added_info_df.to_csv('added_info.csv', index=True)

In [97]:
title_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 312 entries, 7 to 199
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       312 non-null    object
 1   title         312 non-null    object
 2   type          312 non-null    object
 3   cast          312 non-null    object
 4   release_year  312 non-null    int64
 5   rating        312 non-null    object
 6   duration      312 non-null    object
 7   description   312 non-null    object
dtypes: int64(1), object(7)
memory usage: 21.9+ KB